In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [14]:

df = pd.read_csv('/kaggle/input/iris-data/IRIS.csv')

In [15]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [16]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [17]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [19]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [20]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [21]:
df['species'].replace({'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3},inplace=True)

<ipython-input-21-203de560083c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['species'].replace({'Iris-setosa':1,'Iris-versicolor':2,'Iris-virginica':3},inplace=True)
<ipython-input-21-203de560083c>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'].replace({'Iris-setosa':1,'Iris-

In [22]:
df

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['sepal_length','sepal_width','petal_length','petal_width']],df['species'],test_size=0.2)

In [24]:
len(x_train)

120

In [25]:
len(y_train)

120

In [26]:
len(x_test)

30

In [27]:
len(y_test)

30

In [28]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
lr.predict(x_test)

array([1, 2, 3, 1, 1, 3, 3, 3, 1, 1, 2, 3, 1, 3, 3, 1, 1, 1, 1, 3, 2, 2,
       3, 1, 3, 2, 1, 1, 3, 2])

In [30]:
x_test #Iris-setosa:'1',Iris-versicolor:'2',Iris-virginica:'3'

sepal_length  sepal_width  petal_length  petal_width
14            5.8          4.0           1.2          0.2
87            6.3          2.3           4.4          1.3
149           5.9          3.0           5.1          1.8
11            4.8          3.4           1.6          0.2
7             5.0          3.4           1.5          0.2
127           6.1          3.0           4.9          1.8
129           7.2          3.0           5.8          1.6
118           7.7          2.6           6.9          2.3
9             4.9          3.1           1.5          0.1
1             4.9          3.0           1.4          0.2
91            6.1          3.0           4.6          1.4
146           6.3          2.5           5.0          1.9
3             4.6          3.1           1.5          0.2
77            6.7          3.0           5.0          1.7
143           6.8          3.2           5.9          2.3
30            4.8          3.1           1.6          0.2
19            5.1          3.8           1.5          0.3
4             5.0          3.6           1.4          0.2
46            5.1          3.8           1.6          0.2
70            5.9          3.2           4.8          1.8
89            5.5          2.5           4.0          1.3
88            5.6          3.0           4.1          1.3
144           6.7          3.3           5.7          2.5
34            4.9          3.1           1.5          0.1
101           5.8          2.7           5.1          1.9
98            5.1          2.5           3.0          1.1
39            5.1          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
110           6.5          3.2           5.1          2.0
94            5.6          2.7           4.2          1.3

In [31]:
lr.predict([[8.1,4.8,2.5,1.3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [32]:
lr.predict(x_test)

array([1, 2, 3, 1, 1, 3, 3, 3, 1, 1, 2, 3, 1, 3, 3, 1, 1, 1, 1, 3, 2, 2,
       3, 1, 3, 2, 1, 1, 3, 2])

In [33]:
lr.predict([[5.1,4.8,2.5,1.3]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

In [34]:
lr.score(x_test,y_test)

0.9333333333333333